project_id = "jcpcxhmmmetkvnmzwtdw"

[functions.classify-feedback]
verify_jwt = false

[functions.ingest-reddit]
verify_jwt = false

[functions.ingest-msqa]
verify_jwt = false

[functions.generate-weekly-report]
verify_jwt = false

[functions.ingest-feedback-portal]
verify_jwt = false

[functions.ingest-sprinklr]
verify_jwt = false

[functions.upload-sprinklr-csv]
verify_jwt = false
